org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=1.21.11
minecraft_version_range=[1.21,1.22)
forge_version=61.1.7
mapping_channel=official
mapping_version=1.21.11
mod_id=essencethief
mod_name=Essence Thief RPG
mod_license=MIT
mod_version=0.2.7
mod_group_id=com.akitaattribute.essencethief
mod_authors=AkitaAttribute
mod_description=Reusable essence XP-orb wrappers and colored rising entity trails.
